// app/layout.js

// CAMBIO AQUI: Importa Inter desde 'next/font/google'
import { Inter } from 'next/font/google'
import { Analytics } from '@vercel/analytics/next'

import './globals.css' // Tus estilos globales

// Configura la fuente Inter (asegúrate de que subsets esté configurado)
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Usa la clase generada por Inter */}
      <body className={inter.className}>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
